### PR TITLE
Fixed Some minor Issues with Installer Tool

### PR DESCRIPTION
**Pull request by ROBdk97**
+ Fixed: If no "g_language" is found. Nothing happened.
+ Added ability to Remove "g_language" entry with 13.
+ Minor Clean-up

### CODE REVIEW

**Comment by Dymerz** [comment]
Nice work, I don't really love Batch (who does?) so this work is really appreciated :)

**Comment by Dymerz** [comment]
I currently don't have access to a Windows environment and I've heard that [The voice of the Ship is broken when a translation is used](https://issue-council.robertsspaceindustries.com/projects/STAR-CITIZEN/issues/STARC-86490). Could modify the script to add the `g_languageAudio = english` in the `user.cfg` if it doesn't exist?

**Comment by ROBdk97** [comment]
Well I am also not a fan of batch^^
I may take a look at the `g_languageAudio = english`

**Comment by Dymerz** [comment]
Finally, I managed to get a Windows, we're good

**Pull request merged**
