### PR TITLE
Medical+Kiosk Terminal text improvements

### PR DESCRIPTION
**Pull request by Auhrus**
Medical Interfaces +
Kiosk terminals improved +
smaller other improvements

### CODE REVIEW

**Review by ROBdk97 — APPROVED** [review]
Didn't we fix the landing pads in the past?
Looks good!

**Comment by Auhrus** [comment]
Yes, I also think I've seen this before.

**Comment by Dymerz** [comment]
From what I can see, these lines  (`57952-57940`) has not been modified since the initial German commit (https://github.com/Dymerz/StarCitizen-Localization/commit/cc6c3eb)

**Comment by Auhrus** [comment]
Fixed the missing Entries from "Validate global.ini Entries" check
Entries edited/added

**Pull request merged**
