### PR TITLE
Update File and tool to upgrade versions

### PR DESCRIPTION
**Pull request by juancmontes**
Spanish file upgraded to 3.21 and some text fixed.
Tool to upgrade directly global.ini files with the last english version.

### CODE REVIEW

**Comment by ROBdk97** [comment]
It's probably not necessary to add such a program to the repo directly.
And why an entire Forms app? Just use a simple .Net console app without top-level statements.

```cs
using System.Text;

Console.WriteLine("Enter the path to the input english global.ini:");
string inputFilePath = Console.ReadLine();
Console.WriteLine("Enter the path to the output file (de, es, ...):");
string langFilePath = Console.ReadLine();
inputFilePath = inputFilePath.Replace("\"", "");
langFilePath = langFilePath.Replace("\"", "");
await AddMissingEntries(inputFilePath, langFilePath);
Console.WriteLine("Done!");
Console.ReadLine();

static async Task AddMissingEntries(string inputFilePath, string outputFilePath)
{
    var readIn = Task.Run(() => File.ReadAllLinesAsync(inputFilePath));
    var readOut = Task.Run(() => File.ReadAllLinesAsync(outputFilePath));

    var file1Lines = await readIn;
    var file2Lines = await readOut;

    var file1Dict = file1Lines.Select(line => line.Split('=', 2)).ToDictionary(split => split[0], split => split[1]);

    var file2Dict = file2Lines.Select(line => line.Split('=', 2)).ToDictionary(split => split[0], split => split[1]);

    var outputBuilder = new StringBuilder();

    foreach (var line in file1Lines)
    {
        var key = line.Split('=')[0];
        if (file2Dict.TryGetValue(key, out string? value))
            outputBuilder.AppendLine($"{key}={value}");
        else
        {
            Console.WriteLine($"Adding line {key}: {file1Dict[key]}");
            outputBuilder.AppendLine(line);
        }
    }
    await File.WriteAllTextAsync(outputFilePath, outputBuilder.ToString(), new UTF8Encoding(true));
}
```

**Comment by juancmontes** [comment]
I know, i had a console version, but maybe for some people is more easy use it from form window.

**Comment by Dymerz** [comment]
@juancmontes First thank you for your contribution.

I concur with @ROBdk97 as this is not the right place for this tool while a visual interface would be great, compiled executables highly likely to be blocked by antivirus software

**Comment by Dymerz** [comment]
I'd be happy to integrate such an application into this project, but I think it's better to host it on another repository, so I suggest you create a dedicated one

**Comment by juancmontes** [comment]
I moved the project of the tool to: https://github.com/juancmontes/SCUpgradeTranslationTool

**Pull request merged**
