### PR TITLE
revert line 6-7 and repairing hat/Hut in german

### PR DESCRIPTION
**Pull request by electronicfreak**

### CODE REVIEW

**Comment by ROBdk97** [comment]
I already repaired hat and Hut (at least I hope so)

**Comment by electronicfreak** [comment]
so, then should be no conflicts there^^

**Comment by ROBdk97** [comment]
Okay you found some more Hut issues. I manually merged the global.ini for German for us see latest commit in #25

**Comment by Dymerz** [comment]
@all-contributors Please add @electronicfreak and @ROBdk97  for translation

**Comment by Dymerz** [comment]
@all-contributors Please add @ROBdk97 for translation

**Pull request merged**
