### PR TITLE
Followup to #101 (ENG)

### PR DESCRIPTION
**Pull request by ROBdk97**
This is a Followup to #101 

Removed the Spaces at the end of lines to have a better view about the real changes

### CODE REVIEW

**Comment by Auhrus** [comment]
I would have actually said we leave the spaces in since you can see the change without space in this commit.
https://github.com/Dymerz/StarCitizen-Localization/pull/101/commits/bd7aeee00ba89061d90f0c1dac7f7d27d835d420
If again a new version comes one must remove these again and I think they will have thought what with these Spaces as a placeholder or simply around something better to format! And of course for perhaps archive purposes to ensure simply that one has these older files again available.

**Comment by ROBdk97** [comment]
The spaces at the end of the lines look too random to make sense.

**Comment by Auhrus** [comment]
I don't know, but it's an extra step to do it again and again when a new version comes out. I'm just saying.

**Comment by ROBdk97** [comment]
Regex: "[ ]+$"
Not much work

**Comment by Auhrus** [comment]
Yes ok, anyway commit again and it is then just no longer original. Then we do it that way. 👍

**Comment by Dymerz** [comment]
I prefer to keep the file as it comes from the original game. This way, we won't interfere with things we might not be aware of, and the file can truly be called "original."

If you don't want to see whitespace in the diff, you can still hide them by adding `?w=1` to the URL.

**Pull request closed without merging**
