### PR TITLE
Emote commands in English + Small visual improvements

### PR DESCRIPTION
**Pull request by Auhrus**
- Chat emote commands corrected
- Small äöü replaced by capital letters e.g. from (in the menu) ZURüCK to ZURÜCK
- other small improvements to the menu text

### CODE REVIEW

**Review by ROBdk97 — APPROVED** [review]

**Review by electronicfreak — CHANGES_REQUESTED** [review]
to much capital umlaute, plz change

**Comment by ROBdk97** [comment]
> to much capital umlaute, plz change

They are there so they even show up in game. Lowercase is often bugged.

**Comment by Auhrus** [comment]
> to much capital umlaute, plz change

Exactly what @ROBdk97 said.  In the game, the main menu says "ZURüCK" to go back and that looks strange, so I put the ü as a capital Ü so that the button says "ZURÜCK".

**Comment by ROBdk97** [comment]
@electronicfreak what is now up with this? We gave you the reason for the capital umlauts

**Review by ROBdk97 — APPROVED** [review]

**Comment by ROBdk97** [comment]
@Dymerz can you help us pls.?

**Review by ROBdk97 — APPROVED** [review]

**Comment by Auhrus** [comment]
Since @electronicfreak unfortunately no longer responds here, the changes suggested here were added with Commit ce27ab2be3cef5a69613f9c92439883401ea9765 to #168 and are ready to merge there.

**Pull request closed without merging**
