### PR TITLE
Better Spelling

### PR DESCRIPTION
**Pull request by syntafin**

### CODE REVIEW

**Comment by ROBdk97** [comment]
Thanks^^

**Comment by syntafin** [comment]
> Thanks, this looks good^^

It's way not complete, just some strings I noticed when I quickly checked it. But more eyes can find more :) !

**Comment by ROBdk97** [comment]
I also adjusted a lot more in #5

**Comment by syntafin** [comment]
Then we should combine the to PR to a bigger one :)

**Comment by Dymerz** [comment]
Sound good!

**Pull request merged**
