### PR TITLE
lines 62002 to 62108

### PR DESCRIPTION
**Pull request by awar**

### CODE REVIEW

**Comment by Anyma6** [comment]
Why does this commit also include changes to the French file?

**Comment by awar** [comment]
Sincertly i don't  know

**Comment by Dymerz** [comment]
It's caused by the [French pipeline update](https://github.com/Dymerz/StarCitizen-Localization/blob/main/.github/workflows/update-french.yaml) that runs on both this project and all its forks. 

This pipeline checks if the `global.ini` file in specific repositories has changed, and if it has, it commits and pushes the changes. 

However, this pipeline shouldn't run on forks, as it creates a different commit ID with no differences (since both the main pipeline and fork would receive the same changes).

The issue we're facing here is that the pipeline fails to execute on the main repository, which is causing a difference.

I will fix the pipeline to not run on forks, so we shouldn't see this behavior anymore.

**Comment by Anyma6** [comment]
I had imagined it, as I noticed that this file was also modified on my fork. To be safe, I preferred a confirmation 👍

**Comment by Dymerz** [comment]
Fixed in #70

**Pull request merged**
