### PR TITLE
better german translation

### PR DESCRIPTION
**Pull request by Jack-mk**

### CODE REVIEW

**Review by ROBdk97 — COMMENTED** [review]
Why do you sometimes remove ü/ä/ö?

**Review by ROBdk97 — APPROVED** [review]
Looks good

**Comment by xXSuspectXx** [comment]
i have added another german global .ini. i hope you can do anything with that.

https://github.com/xXSuspectXx/StarCitizen-Localization/blob/main/global.ini

**Comment by ROBdk97** [comment]
> i have added another german global .ini. i hope you can do anything with that.
> 
> https://github.com/xXSuspectXx/StarCitizen-Localization/blob/main/global.ini

I will have a look at it tonight.

**Comment by Jack-mk** [comment]
The font for interaction don't render ÖÄÜß and also the big font in fleet manager terminal.

**Comment by Jack-mk** [comment]
> > i have added another german global .ini. i hope you can do anything with that.
> > https://github.com/xXSuspectXx/StarCitizen-Localization/blob/main/global.ini
> 
> I will have a look at it tonight.

Looks like most special keywords (~) are still messed up. This is fixed in the current global.ini

**Comment by ROBdk97** [comment]
> The font for interaction don't render ÖÄÜß and also the big font in fleet manager terminal.

so it only works in Flash UI and not yet in Building Blocks?

**Pull request closed without merging**
