### PR TITLE
Added instructions in Italian

### PR DESCRIPTION
**Pull request by Anyma6**
Added instructions in Italian and added contribuing.md file in Italian

### CODE REVIEW

**Comment by Dymerz** [comment]
Awesome!

Would you plan to add the global.ini in this PR?

**Comment by Anyma6** [comment]
Yes, we are organizing with my ORG and with the Italian community to do it

**Comment by Dymerz** [comment]
I've joined the Italian Discord, and it would be great if we could get in touch through there

**Comment by Anyma6** [comment]
of course, we are trying to involve as many people as possible. the org I am part of has 1200 people, we will also publish the repo in other Italian communities

**Comment by Dymerz** [comment]
@all-contributors please add @Anyma6 for translation

**Pull request merged**
