### PR TITLE
Big update

### PR DESCRIPTION
**Pull request by InterPlay02**
Changed lots of words to fit their utility better, translated ship function focus, and a lot more.

### CODE REVIEW

**Comment by Dymerz** [comment]
Hey @InterPlay02 thanks for your contribution! :smile: 
@Nxzzin can you check this one?

**Comment by Dymerz** [comment]
Outch,  it seems there's a [773 missing placeholder](https://github.com/Dymerz/StarCitizen-Localization/actions/runs/6738084349/job/18319944706?pr=147), perhaps this warrants a dedicated pull request later

**Comment by Nxzzin** [comment]
@InterPlay02 por favor contate @m0t4 no discord, não vou fazer modificações até que ele de sinal de vida na unificação, se ele demorar demais me chama no ds @Nxzzin .  Obrigado pela contribuição!

**Comment by Dymerz** [comment]
@Nxzzin don't close unresolved PR, we should talk and report the status here in `comment` and if it's really necessary do a call

**Comment by Nxzzin** [comment]
@Dymerz well i've his contact, i don't see any reasons to keep it opened. Also, we're resolving some merge with @danielgmota

**Comment by InterPlay02** [comment]
I'm sending more updates. If you could take a look.

**Comment by ROBdk97** [comment]
Consider making it a draft instead of opening and closing the pull request.

**Comment by Nxzzin** [comment]
Everytime i close a PR it's because i've already choose and merged the changes into my local global.ini, and later i send it to github. I now i'm working in a weird way, but its easier for me to supervise.

**Pull request closed without merging**
