### PR TITLE
Updating German

### PR DESCRIPTION
**Pull request by ROBdk97**
Some Custom Translations
Added Missing Entries (May not be Translated!)
Hopefully fixed all "~mission(SOMETHING)" and so on

### CODE REVIEW

**Comment by ROBdk97** [comment]
Fixed UTF-8 to UTF-8-BOM again
Added Readme Entry to german instructions

**Comment by ROBdk97** [comment]
Fixed Interaction_InteractionMode

**Comment by ROBdk97** [comment]
Fixed some Further Issues

**Comment by ROBdk97** [comment]
Further Improvements to german

**Comment by ROBdk97** [comment]
Updated further entries

**Comment by Dymerz** [comment]
@ROBdk97 
Thanks you so much for your help on German translations!
Could you give me commit permission please?

**Comment by ROBdk97** [comment]
You Cant?

**Comment by Dymerz** [comment]
I just wanted to update the German flag on the README.md. There should be a checkbox labeled "Allow edits from maintainers" This option allows me to commit changes if necessary.

**Comment by ROBdk97** [comment]
Okay I am to stupid to find this so I changed hopefully what you wanted to change xD

**Comment by ROBdk97** [comment]
Screenshot 2023-10-12 102107
And it is checked

**Pull request merged**
