### PR TITLE
Improve install script

### PR DESCRIPTION
**Pull request by Dymerz**

### CODE REVIEW

**Comment by ROBdk97** [comment]
Great changes. Localizing the installer sounds like a great Idea. Sadly I still can't run PowerShell scripts to test it.

**Comment by ROBdk97** [comment]
German looks good in the file

**Comment by Dymerz** [comment]
@Nxzzin @Anyma6  could you take a look at the localization?

**Comment by Anyma6** [comment]
sure, I'll check everything by tomorrow evening... unfortunately I can't before that

**Comment by Anyma6** [comment]
The script works well, correctly translated. The problem is that it is blocked from running for security (on most computers) because script execution is disabled by default.

A simple workaround could be to copy all the contents of the powershell file into a new powershell window and run it directly.

**Comment by ROBdk97** [comment]
I also raised that issue in #157

**Pull request merged**
