### PR TITLE
Added ✅in supported languages and added missing readme links

### PR DESCRIPTION
**Pull request by Autovot**

### CODE REVIEW

**Comment by Dymerz** [comment]
Ok for README links but Italian is not supported yet, the [globals.ini](data/Localization/italian_(italy)/global.ini) in the repo has only a few lines translated (see #35 )

**Comment by Autovot** [comment]
ok, I hadn't seen it, I assumed it was there, since I already had the .ini, thanks

**Comment by Dymerz** [comment]
No problem, we can keep this PR in the meantime

**Review by electronicfreak — APPROVED** [review]
seems legit

**Comment by Dymerz** [comment]
I will fix those conflicts

**Pull request closed without merging**
