### PR TITLE
3.21.1 English & German

### PR DESCRIPTION
**Pull request by ROBdk97**
Complete English
German till 60860 will do rest later

@Auhrus you want to check the German part?

(Pull delayed until the release of 3.21.1)

### CODE REVIEW

**Comment by ROBdk97** [comment]
Fixed incorrect entries and added some translations in the process,
Also fixed some existing translations and we may need to take a look at the tutorial because it seems like they changed the texts a lot.

Will continue to translate the last new entries.

**Comment by ROBdk97** [comment]
If all reviews pass and 3.21.1 comes out. Ready to push.

**Comment by Auhrus** [comment]
Sorry for the late response. Have you already gone through all the new entries @ROBdk97?

**Comment by ROBdk97** [comment]
> Sorry for the late response. Have you already gone through all the new entries @ROBdk97?

Yeah, should be done. Would be nice if you check if I missed anything ^^

**Review by Auhrus — APPROVED** [review]
So it looks good from my side. 👍

I just don't know if we should wait until it's LIVE again, because maybe something will change. Especially since the branch "main" has only ever been used for the LIVE patch and not for preview/PTU.

**Comment by ROBdk97** [comment]
Would wait until the patch goes live.

**Comment by Auhrus** [comment]
Top that's exactly what I meant then it goes 👍

**Comment by ROBdk97** [comment]
@electronicfreak this is for 3.21.1 not for 3.20. Why did you push it already?

**Pull request merged**
