### PR TITLE
Some more incorrect translation fixed

### PR DESCRIPTION
**Pull request by syntafin**
Fixed some wrong translation I found recently. We should not translate names of places like "Shallow Frontier Station" to "Station Flache Grenze".
Will continue to check the automated translations later today

### CODE REVIEW

**Comment by ROBdk97** [comment]
Looks good!
Short Question: what do you think? Should we keep the English name for items?

**Comment by syntafin** [comment]
> Looks good!
> Short Question: what do you think? Should we keep the English name for items?

Location names should not be translated, but with item names, it's maybe harder to decide, example the Medpens, idk if we should translate them, ammunition or weapons could be translated.

**Comment by ROBdk97** [comment]
Yes, I agree Location names shouldn't be translated. 
The question is what to translate and what not^^

**Review by ROBdk97 — APPROVED** [review]
Some vehicle names are still wrong but should be fixed in mine hopefully after I am done.

**Comment by Dymerz** [comment]
> > Looks good!
> > Short Question: what do you think? Should we keep the English name for items?
> 
> Location names should not be translated, but with item names, it's maybe harder to decide, example the Medpens, idk if we should translate them, ammunition or weapons could be translated.

I agree, name should remains unchanged, for the Medpens it's a good questions..
We should create a guideline

**Pull request merged**
