### PR TITLE
Update Brazilian 3.22 9003376

### PR DESCRIPTION
**Pull request by Nxzzin**
Changes:
- Updated to 3.22.0-PTU.9003376
- Fixes in description and contract objectives, Especially Siege of Orison
- Fixes in Items descriptions
- Fixes in SRV
- Fixes in Estructural Salvage
- Various corrections at Keybindings
- Fixes in Arena Commander
- Minor fixes in Notifications and UI
- Fixes in category filter at kiosk's

### CODE REVIEW

**Comment by ROBdk97** [comment]
Btw. we have a PTU Branch

**Comment by Nxzzin** [comment]
@ROBdk97 don't know why it failed but ok

**Comment by ROBdk97** [comment]
Because it's the main branch

**Comment by Nxzzin** [comment]
What exactly do ive to do here?

**Comment by ROBdk97** [comment]
You need to pull the request into the PTU branch, not the main branch.
The main branch has different entries and does not contain the English global.ini which is currently on the put, because of this the Validate global.ini / Validate global.ini Entries GitHub Action says you are missing entries, and so on.

If you want to know which entries are missing or have errors, you can click on the Details button next to the failed check.

**Comment by Nxzzin** [comment]
I see, thanks!

**Pull request closed without merging**
