### PR TITLE
es-es_3.23.1-LIVE.9204897

### PR DESCRIPTION
**Pull request by danidomen**

### CODE REVIEW

**Comment by ROBdk97** [comment]
# There seem to be some issues:

Validating keys...
  - Unable to find key "hud_InboundMissile"
  - Unable to find key "salvage_HUD_TargetStatus_Valid"
  - Unable to find key "vehicle_NameMisc_Fury_LX"
  => 🔥 One or more keys are missing in source file

Validating "~name(parameter)" placeholders...
  - Unable to find placeholder "~mission(Contractor|Danger)" in "FTL_delivery_desc_0001"
  - Unable to find placeholder "~mission(Location|Address)" in "Redwind_internaldelivery_dc_desc_001"
  - Unable to find placeholder "~mission(Location|Address)" in "Redwind_internaldelivery_dc_desc_002"
  - Unable to find placeholder "~mission(Location|Address)" in "Redwind_internaldelivery_dc_desc_003"
  - Unable to find placeholder "~mission(Location|Address)" in "Redwind_internaldelivery_dc_desc_004"
  - Unable to find placeholder "~mission(Location|Address)" in "Redwind_internaldelivery_dc_desc_005"
  - Unable to find placeholder "~mission(targetcount)" in "RetakeLocation_Neutralize_obj_02_hud"
  - Unable to find placeholder "~mission(targetcountinterior)" in "RetakeLocation_Neutralize_obj_03_hud"
  - Unable to find placeholder "~mission(TargetName)" in "Roughready_bounty_desc_002"
  - Unable to find placeholder "~mission(TargetName|Last)" in "Roughready_bounty_desc_002"
  - Unable to find placeholder "~mission(TargetName|Last)" in "Roughready_bounty_desc_002"
  - Unable to find placeholder "~mission(Location|Address)" in "Roughready_bounty_desc_002"
  - Unable to find placeholder "~mission(TargetName|Last)" in "Roughready_bounty_desc_002"
  - Unable to find placeholder "~mission(RaceType|ScrambleRaceASOP)" in "ScrambleRace_Desc_Suicide_01"
  - Unable to find placeholder "~action(spaceship_movement|v_ifcs_throttle_swap_mode)" in "Tut03_Part02_Hint12_MaintainSpeed"
  - Unable to find placeholder "~mission(Pickup1|Address)" in "Xenothreat_theft_outpost_cfp_desc_001"
  - Unable to find placeholder "~mission(item)" in "Xenothreat_theft_outpost_cfp_desc_001"
  - Unable to find placeholder "~mission(Dropoff1|Address)" in "Xenothreat_theft_outpost_cfp_desc_001"
  - Unable to find placeholder "~mission(Pickup1|Address)" in "Xenothreat_theft_station_roughready_desc_001"
  - Unable to find placeholder "~mission(item)" in "Xenothreat_theft_station_roughready_desc_001"
  - Unable to find placeholder "~mission(Dropoff1|Address)" in "Xenothreat_theft_station_roughready_desc_001"
  - Unable to find placeholder "~mission(ARacerSurvivesRace)" in "aracersurvivesrace_obj_long_01,P"
  - Unable to find placeholder "~mission(Contractor|AssassinationTimed)" in "assassin_desc_0004"
  - Unable to find placeholder "~mission(Location|Address)" in "basesweep_obj_short_02"
  - Unable to find placeholder "~mission(dropoff1|address)" in "bitzeros_RetrieveConsignment_desc_001"
  - Unable to find placeholder "~mission(Danger)" in "blackboxillegal_desc_0005"
  - Unable to find placeholder "~mission(Timed)" in "blackboxillegal_desc_0005"
  - Unable to find placeholder "~mission(Location|Address)" in "commarray_hack_desc_0004"
  - Unable to find placeholder "~mission(Location)" in "confirmkill_desc_0001"
  - Unable to find placeholder "~mission(Danger)" in "confirmkill_desc_0001"
  - Unable to find placeholder "~mission(Timed)" in "confirmkill_desc_0005"
  - Unable to find placeholder "~mission(TargetName|Last)" in "confirmkill_location_0003"
  - Unable to find placeholder "~mission(TargetName|NickOrFirst)" in "confirmkill_timed_0002"
  - Unable to find placeholder "~mission(Reference)" in "covalexrand_desc_0005"
  - Unable to find placeholder "~mission(Danger)" in "crusader_bounty_desc_004"
  - Unable to find placeholder "~mission(Contractor|BountyTimed)" in "crusader_bounty_desc_004"
  - Unable to find placeholder "~mission(MissionCluster|Address)" in "crusader_platform_EliminateAll_description_001"
  - Unable to find placeholder "~mission(MissionCluster|Name)" in "crusader_platform_EliminateSpecific_desc"
  - Unable to find placeholder "~mission(Danger)" in "deploypiggyback_desc_0003"
  - Unable to find placeholder "~mission(Contractor|DestroyProbeAmount)" in "destroyprobelegal_desc_0002"
  - Unable to find placeholder "~mission(Contractor|DestroyProbeDanger)" in "destroyprobelegal_desc_0002"
  - Unable to find placeholder "~mission(Contractor|DestroyProbeDanger)" in "destroyprobelegal_desc_0004"
  - Unable to find placeholder "~mission(Contractor|DestroyProbeDanger)" in "destroyprobelegal_desc_0005"
  - Unable to find placeholder "~mission(Wanted)" in "distraction_desc_0001"
  - Unable to find placeholder "~mission(Wanted)" in "distraction_desc_0002"
  - Unable to find placeholder "~mission(Wanted)" in "distraction_desc_0004"
  - Unable to find placeholder "~mission(Location|Address)" in "dusters_basesweep_desc_002"
  - Unable to find placeholder "~action(spectator|spectate_toggle_lock_target|?)" in "ea_ui_spectator_UnlockCamera"
  - Unable to find placeholder "~mission(EliminateSpecificRacerReward)" in "eliminatespecificracer_obj_long_01,P"
  - Unable to find placeholder "~mission(Contractor|Danger)" in "hdactivist_basesweep_desc_002"
  - Unable to find placeholder "~mission(Contractor|BaseSweep)" in "hdactivist_basesweep_desc_004"
  - Unable to find placeholder "~mission(CombatPay)" in "kareahsweep_desc_0004"
  - Unable to find placeholder "~mission(Location)" in "meet_miles_lg_desc_0002"
  - Unable to find placeholder "~mission(Update)" in "mg_clovus_bladesteal_desc_003"
  - Unable to find placeholder "~mission(Contractor|Danger)" in "mg_klim_deliver_drug_desc_0003"
  - Unable to find placeholder "~mission(Contractor|Timed)" in "mg_klim_deliver_drug_desc_0005"
  - Unable to find placeholder "~mission(rush)" in "mg_miles_planetcollect_steal_desc_0005"
  - Unable to find placeholder "~mission(location)" in "mg_miles_spacecollect_steal_desc_0003"
  - Unable to find placeholder "~mission(trouble)" in "mg_miles_spacecollect_steal_desc_0003"
  - Unable to find placeholder "~mission(destination)" in "mg_miles_spacecollect_steal_desc_0003"
  - Unable to find placeholder "~mission(rush)" in "mg_miles_spacecollect_steal_desc_0003"
  - Unable to find placeholder "~mission(trouble)" in "mg_miles_spacecollect_steal_desc_0004"
  - Unable to find placeholder "~mission(trouble)" in "mg_miles_spacecollect_steal_desc_0005"
  - Unable to find placeholder "~mission(rush)" in "mg_miles_spacecollect_steal_desc_0005"
  - Unable to find placeholder "~mission(trouble)" in "mg_miles_spacecollect_steal_desc_0007"
  - Unable to find placeholder "~mission(client)" in "mg_miles_sweeplegal_danger_004"
  - Unable to find placeholder "~mission(location|address)" in "mg_pacheco_DestroyEvidence_desc_001"
  - Unable to find placeholder "~mission(DropOff1|address)" in "mg_ruto_RetrieveConsignment_desc_001"
  - Unable to find placeholder "~mission(location)" in "mg_ruto_blackboxillegal_desc_0005"
  - Unable to find placeholder "~mission(destination)" in "mg_ruto_blackboxillegal_desc_0005"
  - Unable to find placeholder "~mission(trouble)" in "mg_ruto_blackboxillegal_desc_0005"
  - Unable to find placeholder "~mission(threat)" in "mg_ruto_commhack_desc_0002"
  - Unable to find placeholder "~mission(Danger)" in "mg_ruto_confirmkill_desc_0001"
  - Unable to find placeholder "~mission(wanted)" in "mg_ruto_distraction_desc_0001"
  - Unable to find placeholder "~mission(Location)" in "mg_ruto_distraction_desc_0001"
  - Unable to find placeholder "~mission(Location)" in "mg_ruto_distraction_desc_0003"
  - Unable to find placeholder "~mission(oldman)" in "mg_ruto_invite_desc_0001"
  - Unable to find placeholder "~mission(oldman)" in "mg_ruto_invite_desc_0003"
  - Unable to find placeholder "~mission(Timed)" in "mg_ruto_outpost_repair_desc_0003"
  - Unable to find placeholder "~mission(client)" in "mg_ruto_planetcollect_drug_rush_0003"
  - Unable to find placeholder "~mission(rush)" in "mg_ruto_planetcollect_steal_desc_0002"
  - Unable to find placeholder "~mission(Item)" in "mg_ruto_planetcollect_waste_desc_0003"
  - Unable to find placeholder "~mission(danger)" in "mg_ruto_sectorsweep_desc_0004"
  - Unable to find placeholder "~mission(ship)" in "mg_ruto_spacecargo_illegal_danger_0004"
  - Unable to find placeholder "~mission(trouble)" in "mg_ruto_spacecargo_illegal_desc_0005"
  - Unable to find placeholder "~mission(destination)" in "mg_ruto_spacesteal_desc_0004"
  - Unable to find placeholder "~mission(client)" in "mg_ruto_spacesteal_desc_0004"
  - Unable to find placeholder "~mission(CombatPay)" in "outlawsweep_desc_0004"
  - Unable to find placeholder "~mission(Timed)" in "outpost_repair_desc_0001"
  - Unable to find placeholder "~mission(Timed)" in "outpost_repair_desc_0002"
  - Unable to find placeholder "~mission(Danger)" in "planetcollect_drug_desc_0013"
  - Unable to find placeholder "~mission(Item)" in "planetcollect_food_timed_0006"
  - Unable to find placeholder "~mission(Timed)" in "planetcollect_illegalwaste_desc_0004"
  - Unable to find placeholder "~mission(Timed)" in "planetcollect_ore_desc_0007"
  - Unable to find placeholder "~mission(Item)" in "planetcollect_seeds_timed_0006"
  - Unable to find placeholder "~mission(Item)" in "planetcollect_waste_desc_0001"
  - Unable to find placeholder "~mission(Stops)" in "planetcollect_waste_desc_0002"
  - Unable to find placeholder "~mission(Item)" in "planetcollect_waste_desc_0002"
  - Unable to find placeholder "~mission(Item)" in "planetcollect_waste_desc_0003"
  - Unable to find placeholder "~mission(Stops)" in "planetcollect_waste_desc_0006"
  - Unable to find placeholder "~mission(Danger)" in "recoverstolen_space_desc_0006"
  - Unable to find placeholder "~mission(Pickup1|Address)" in "redwind_courier_fromdc_med_desc_001"
  - Unable to find placeholder "~mission(Pickup1)" in "redwind_courier_fromdc_med_desc_001"
  - Unable to find placeholder "~mission(Pickup1)" in "redwind_courier_fromdc_med_desc_001"
  - Unable to find placeholder "~mission(Pickup1|Address)" in "redwind_courier_fromdc_med_desc_001"
  - Unable to find placeholder "~mission(Pickup1|Address)" in "redwind_courier_fromdc_small_desc_001"
  - Unable to find placeholder "~mission(Pickup1)" in "redwind_courier_fromdc_small_desc_001"
  - Unable to find placeholder "~mission(Pickup1)" in "redwind_courier_fromdc_small_desc_001"
  - Unable to find placeholder "~mission(Pickup1|Address)" in "redwind_courier_fromdc_small_desc_001"
  - Unable to find placeholder "~mission(Dropoff1)" in "redwind_courier_todc_med_desc_001"
  - Unable to find placeholder "~mission(Dropoff1|Address)" in "redwind_courier_todc_med_desc_001"
  - Unable to find placeholder "~mission(Dropoff1)" in "redwind_courier_todc_small_desc_001"
  - Unable to find placeholder "~mission(Dropoff1|Address)" in "redwind_courier_todc_small_desc_001"
  - Unable to find placeholder "~mission(TargetName)" in "roughready_bounty_desc_003"
  - Unable to find placeholder "~mission(TargetName|Last)" in "roughready_bounty_desc_003"
  - Unable to find placeholder "~mission(TargetName|Last)" in "roughready_bounty_desc_003"
  - Unable to find placeholder "~mission(Location|Address)" in "roughready_bounty_desc_003"
  - Unable to find placeholder "~mission(TargetName|Last)" in "roughready_bounty_desc_003"
  - Unable to find placeholder "~mission(location|address)" in "roughready_eliminateall_maintenance_desc_01"
  - Unable to find placeholder "~mission(destination)" in "spacesteal_desc_0001"
  - Unable to find placeholder "~mission(Danger)" in "spacesteal_desc_0001"
  - Unable to find placeholder "~mission(Contractor|StealItem)" in "spacesteal_desc_0005"
  - Unable to find placeholder "~mission(Contractor|StealItem)" in "spacesteal_desc_0005"
  - Unable to find placeholder "~mission(XDamageToRacerTarget3)" in "xdamagetoracersinorder_obj_long_01c,P"
  - Unable to find placeholder "~mission(XDamageToRacerTarget3)" in "xdamagetoracersinorder_obj_short_01c,P"
  - Unable to find placeholder "~mission(location|address)" in "xenothreat_eliminateall_CFP_outpost_desc_01"
  - Unable to find placeholder "~mission(location)" in "xenothreat_eliminateall_CFP_outpost_title_01"
  => 🔥 One or more placeholders are missing in source file

Validating "%name" placeholders...
  - Unable to find placeholder "%Is" in "Community_Service_Desc_Long"
  - Unable to find placeholder "%ls" in "Infractions_Grace_0[44](https://github.com/Dymerz/StarCitizen-Localization/actions/runs/9621471732/job/26541672114?pr=310#step:6:45)"
  - Unable to find placeholder "%ls" in "commarray_repair_obj_display_03"
  - Unable to find placeholder "%ird" in "dfm_ui_Result_param_rdPlace"
  - Unable to find placeholder "%ist" in "dfm_ui_Result_param_stPlace"
  - Unable to find placeholder "%ith" in "dfm_ui_Result_param_thPlace"
  - Unable to find placeholder "%is" in "ui_Seconds"
  => 🔥 One or more placeholders are missing in source file

**Comment by danidomen** [comment]
Hi @ROBdk97 i made the changes, but also I found that on some of the ones that says that gives errors like for example this ones:
Redwind_internaldelivery_dc_desc_001
Roughready_bounty_desc_002
Xenothreat_theft_outpost_cfp_desc_001
Xenothreat_theft_station_roughready_desc_001
commarray_hack_desc_0004
redwind_courier_fromdc_med_desc_001

The placeholders are already there

**Comment by ROBdk97** [comment]
Are you sure about that?

**Comment by danidomen** [comment]
> Are you sure about that?

As sure as the one that says is missing, is already on that tags as this screenshot. 
image


Not all, a lot was really missing as the check says, but strange to rise the ones that are complete. If you can give me one time more the listing with the latest changes to check if really is something missing

**Comment by ROBdk97** [comment]
@Dymerz can you take a look?

**Comment by Dymerz** [comment]
The keys reported as errors are indeed invalid. 
In some of your translations, you replaced certain characters with their web-encoded variants (e.g., replacing `"` with `&quot;`). All these encoded characters end with a `;`, which in INI files is used to denote comments. 

For instance, in the following line:
```ini
xenothreat_eliminateall_CFP_outpost_title_01=Orden de muerte: &quot;Ciudadanos&quot; en ~mission(location)
```

The actual value will be interpreted as:
```ini
xenothreat_eliminateall_CFP_outpost_title_01=Orden de muerte: &quot
```

The tool handled this correctly. The game will behave in the same way, ignoring everything after the semicolon (`;`), thereby marking these translations as invalid.

You can find a complete list of all HTML entities [here](https://www.freeformatter.com/html-entities.html#ascii-characters)

**Comment by Dymerz** [comment]
In fact, I noticed that in the original English file there are `;` characters used, this make sense for translation purposes. 
I will make a fix to escape the comment characters.

**Comment by Dymerz** [comment]
I made the fix and now only [3 errors are listed](https://github.com/Dymerz/StarCitizen-Localization/actions/runs/9626225623/job/26551954844?pr=310).

Don't forget to replace the HTML entities with the correct character as I mentioned above.

**Comment by danidomen** [comment]
Hi @Dymerz,

Thanks for the fix at the validation and the tip about html special chars. I've replaced that and the 3 ones listed.

**Comment by Dymerz** [comment]
sounds good to me!

@all-contributors please add @danidomen for translation

**Pull request merged**
