### PR TITLE
German Translation of 3.22.0-PTU

### PR DESCRIPTION
**Pull request by ROBdk97**
State 3.22.0-PTU.8996133

### CODE REVIEW

**Comment by ROBdk97** [comment]
@Auhrus can you look at this? (Somehow I can't assign this to you)

**Comment by Auhrus** [comment]
@electronicfreak
Why did you merge this pull request, there are still open points in it?

**Comment by electronicfreak** [comment]
okay, my bad.

the mergereq wasn't in draft, and looks better than the prevois version.

**Comment by ROBdk97** [comment]
It´s no draft so it can be reviewed. But I can't assign @Auhrus as a reviewer because he does not have the contributor role.

**Comment by ROBdk97** [comment]
Reverted in #195  and resubmitted in #196 so it can be reviewed again.

**Comment by electronicfreak** [comment]
yea i see, i was a bit hasty after i reviewed any changes.

**Pull request merged**
